giftCardIndex = {
    "Americas": {
        "Canada": [
            "Apple iTunes",
            "Google Play",
            "XBox Live",
            "PlayStation Network",
            "Riot Points",
            "Steam Wallet",
            "Razer Gold",
            "Nintendo eShop",
            "Amazon",
            ],
        "US": [
            "Apple iTunes",
            "Google Play",
            "XBox Live",
            "PlayStation Network",
            "Riot Points",
            "Steam Wallet",
            "Nintendo eShop",
            "Amazon",
            ],
        "Mexico": [
            "Apple iTunes",
            "Google Play",
            "XBox Live",
            "Steam Wallet",
            "Razer Gold",
            ],
        "Brazil": [
            "Google Play",
            "XBox Live",
            "PlayStation Network",
            "Riot Points",
            "Steam Wallet",
            "Razer Gold",
            ],
        },
    "Asia": {
        "India": [
            "Google Play",
            "PlayStation Network",
            "Steam Wallet",
            "Razer Gold",
            "Amazon",
            ],
        "Hong Kong": [
            "Apple iTunes",
            "Google Play",
            "XBox Live",
            "PlayStation Network",
            "Steam Wallet",
            "Razer Gold",
            "Nintendo eShop",
            ],
        "Japan": [
            "Apple iTunes",
            "Google Play",
            "XBox Live",
            "PlayStation Network",
            "Steam Wallet",
            "Nintendo eShop",
            "Amazon",
            ],
        "Saudi Arabia": [
            "Apple iTunes",
            "Google Play",
            "XBox Live",
            "PlayStation Network",
            "Steam Wallet",
            ],
        "Taiwan": [
            "Apple iTunes",
            "XBox Live",
            "PlayStation Network",
            "Steam Wallet",
            "Garena Shells",
            ],
        },
    "South East Asia / Oceania": {
        "Indonesia": [
            "Google Play",          
            "PlayStation Network",
            "Steam Wallet",
            "Razer Gold",
            "Garena Shells",
            ],
        "Malaysia": [
            "Google Play",          
            "PlayStation Network",
            "Steam Wallet",
            "Razer Gold",
            "Garena Shells",
            ],
        "Philippines": [
            "Steam Wallet",
            "Razer Gold",
            "Garena Shells",
            ],
        "Singapore": [
            "Apple iTunes",
            "PlayStation Network",
            "Steam Wallet",
            "Razer Gold",
            "Amazon",
            "Garena Shells",
            ],
        "Australia": [
            "Apple iTunes",
            "Google Play",
            "XBox Live",
            "PlayStation Network",
            "Riot Points",
            "Steam Wallet",
            "Razer Gold",
            "Nintendo eShop",
            "Amazon",
            ],
        },
    "Europe": {
        "Ireland": [
            "Apple iTunes",
            "XBox Live",
            "PlayStation Network",
            "Riot Points",
            "Steam Wallet",
            "Razer Gold",
            "Nintendo eShop",
            ],
        "United Kingdom": [
            "Apple iTunes",
            "Google Play",
            "XBox Live",
            "PlayStation Network",
            "Steam Wallet",
            "Nintendo eShop",
            "Amazon",
            ],
        "Turkey": [
            "Apple iTunes",
            "Google Play",
            "XBox Live",
            "Riot Points",
            "Steam Wallet",
            "Razer Gold",
            ],
        },
    }